/** AUTO-GENERATED by scripts/gen-imported.mjs — 勿手改，改 docs/recovered/*.json 后重跑脚本 */
/* eslint-disable */

export interface WorkflowStage {
  id: string
  projectId: string
  name: string
  owner: string
  status: string
  statusLabel: string
  startDate: string | null
  endDate: string | null
  markCols: number[]
}

export interface AccountPlanAccount {
  name: string
  link: string
  note: string
}

export interface AccountPlan {
  projectId: string
  segment: string
  plannedCount: number | null
  activeCount: number | null
  sceneExample: string
  accounts: AccountPlanAccount[]
}

export interface WeeklyScriptRow {
  projectId: string
  week: string
  rowIndex: number
  [key: string]: string | number
}

export interface DistributionRecord {
  id: string
  projectId: string
  account: string
  publishDate: string | null
  videoUrl: string
  naturalViews: number | null
  paidViews: number
  screenshot: string
  adCompleteTime: string
  note: string
  engagementRate: number | null
  retention3s: number | null
}

export interface AccountMonitorRow {
  account: string
  projectId: string
  postCount: number
  totalPaidViews: number
  totalNaturalViews: number
  avgEngagementRate: number | null
  avgRetention3s: number | null
  lastPublish: string | null
}

export const importSummary = {
  "recoveredFrom": "dojo-web-release.tar.gz / dist/assets/index-D_9QqzGF.js (线上 2026-08-09 构建)",
  "generatedBy": "scripts/gen-imported.mjs",
  "counts": {
    "workflowStages": 0,
    "accountPlans": 0,
    "weeklyScripts": {
      "W1": 0,
      "W2": 0,
      "W3": 0,
      "W4": 0,
      "W5": 0
    },
    "distributionRecords": 0,
    "accountMonitor": 0,
    "timelineStart": "2026-08-04",
    "timelineEnd": "2026-08-04"
  }
} as const

export const timelineStart = "2026-08-04"
export const timelineEnd = "2026-08-04"

export const workflowStages: WorkflowStage[] = []

export const accountPlans: AccountPlan[] = []

export const weeklyScripts: Record<string, WeeklyScriptRow[]> = {
  "W1": [],
  "W2": [],
  "W3": [],
  "W4": [],
  "W5": []
}

export const distributionRecords: DistributionRecord[] = []

export const accountMonitor: AccountMonitorRow[] = []
