/** AUTO-GENERATED by scripts/import-ads.mjs — 勿手改，改 Excel 后重跑 npm run import:ads */
/* eslint-disable */

export interface AdTarget {
  id: string
  project: string
  region: string
  product: string
  targetViews: number | null
  currentViews: number | null
  currentCount: number | null
  totalCount: number | null
  countFinished: boolean
  viewsRate: number | null
  countRate: number | null
  remainingViews: number | null
  updatedAt: string | null
  updatedAtText: string
  deadline: string | null
  deadlineText: string
  adPlatformViews: number | null
  finished: boolean
  batch: string | null
}

export interface AdVideo {
  id: string
  batch: string
  date: string | null
  platform: string
  device: string
  accountUrl: string
  videoUrl: string
  content: string
  naturalViews: number | null
  views: number | null
  code: string
  region: string
  note: string
  feedback: string
  status: string
}

export interface AdBatch {
  batch: string
  videoCount: number
  deliveredCount: number
  firstDate: string | null
  lastDate: string | null
  totalNaturalViews: number
  totalViews: number
  videos: AdVideo[]
}

export interface AdTimelineItem {
  id: string
  name: string
  project: string
  region: string
  product: string
  startDate: string
  endDate: string
  status: string
  viewsRate: number | null
  currentViews: number | null
  targetViews: number | null
  videoCount: number | null
}

export interface AdAccount {
  device: string
  accountUrl: string
  platform: string
  batches: string[]
  videoCount: number
  deliveredCount: number
  totalNaturalViews: number
  totalViews: number
  avgNaturalViews: number | null
  firstDate: string | null
  lastDate: string | null
}

export const adSummary = {
  "importedAt": "2026-08-07T16:31:01.300Z",
  "sourceFile": "2049 投流.xlsx",
  "counts": {
    "targets": 0,
    "batches": 0,
    "videos": 0,
    "accounts": 0,
    "timeline": 0
  },
  "totals": {
    "targetViews": 60466829,
    "currentViews": 66140247
  }
} as const

export const adTargets: AdTarget[] = []

export const adTimeline: AdTimelineItem[] = []

export const adAccounts: AdAccount[] = []

export const adVideos: AdVideo[] = []

export const adBatches: Omit<AdBatch, 'videos'>[] = []
