# Pack Dojo release for Ubuntu deploy → Desktop\dojo-web-release.tgz
$ErrorActionPreference = 'Stop'
$OutputEncoding = [Console]::OutputEncoding = [Text.Encoding]::UTF8

$nodeDir = 'J:\BaiduNetdiskDownload\coding\.tools\node'
if (Test-Path $nodeDir) { $env:PATH = "$nodeDir;" + $env:PATH }

$root = 'J:\BaiduNetdiskDownload\coding\Dojo-rebuild'
$web = "$root\dojo-web"
$release = "$root\release"
$stage = "$release\dojo-web-release"
$desktop = [Environment]::GetFolderPath('Desktop')
$tarballName = 'dojo-web-release.tgz'
$tarballDesktop = Join-Path $desktop $tarballName
$tarballLocal = Join-Path $release $tarballName

Set-Location $web

# 生产走 Nginx 反代，禁止把密钥打进前端包
# 注意：勿用 $envXxx 变量名，PowerShell 会当成 $env:Xxx 环境变量
$prodLocalFile = Join-Path $web '.env.production.local'
@('# auto-generated by pack-release.ps1 — 密钥只进 secrets.env，不进 bundle') |
  Set-Content -LiteralPath $prodLocalFile -Encoding UTF8
Write-Host '>> .env.production.local cleared (proxy-only build)'

# 用本地 .bin，避开 corepack pnpm 强制 install / approve-builds
Write-Host '>> vue-tsc + vite build'
$bin = Join-Path $web 'node_modules\.bin'
& (Join-Path $bin 'vue-tsc.CMD') --noEmit
if ($LASTEXITCODE -ne 0) { throw 'vue-tsc failed' }
& (Join-Path $bin 'vite.CMD') build
if ($LASTEXITCODE -ne 0) { throw 'vite build failed' }

Write-Host '>> stage release'
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Path $stage | Out-Null
Copy-Item -Recurse (Join-Path $web 'dist') (Join-Path $stage 'dist')
Copy-Item (Join-Path $root 'scripts\deploy\nginx-dojo.conf') (Join-Path $stage 'nginx-dojo.conf')
Copy-Item (Join-Path $root 'scripts\deploy\install-on-server.sh') (Join-Path $stage 'install-on-server.sh')
Copy-Item (Join-Path $root 'scripts\deploy\secrets.env.example') (Join-Path $stage 'secrets.env.example')

# 可选：从本机 .env.local 抽出密钥，仅供服务器 nginx secrets.env（不进 dist）
# 注意：勿用 $localXxx / $envXxx 变量名（PowerShell 会解析成 $local: / $env: 作用域）
$dotenvLocalPath = Join-Path $web '.env.local'
$secretsOut = Join-Path $stage 'secrets.env'
if (Test-Path -LiteralPath $dotenvLocalPath) {
  $m1 = Select-String -LiteralPath $dotenvLocalPath -Pattern '^VITE_DEEPSEEK_API_KEY=(.+)$' | Select-Object -First 1
  $m2 = Select-String -LiteralPath $dotenvLocalPath -Pattern '^VITE_RAPIDAPI_KEY=(.+)$' | Select-Object -First 1
  $ds = if ($m1) { $m1.Matches.Groups[1].Value.Trim() } else { $null }
  $rp = if ($m2) { $m2.Matches.Groups[1].Value.Trim() } else { $null }
  if ($ds -and $rp -and $ds -notmatch 'REPLACE' -and $rp -notmatch 'REPLACE') {
    @("DEEPSEEK_API_KEY=$ds", "RAPIDAPI_KEY=$rp") | Set-Content -LiteralPath $secretsOut -Encoding UTF8
    Write-Host '>> secrets.env (for nginx only)'
  } else {
    Write-Host '>> skip secrets.env (no valid keys in .env.local)'
  }
}

# 写入 VERSION.txt，便于服务器 curl 验收
$indexHtml = Join-Path $web 'dist\index.html'
$mainJs = if (Test-Path $indexHtml) {
  $m = Select-String -Path $indexHtml -Pattern 'src="/assets/(index-[^"]+\.js)"' | Select-Object -First 1
  if ($m) { $m.Matches.Groups[1].Value } else { 'unknown' }
} else { 'unknown' }
$reviewJs = Get-ChildItem (Join-Path $web 'dist\assets') -Filter 'review-*.js' -ErrorAction SilentlyContinue |
  Select-Object -First 1 -ExpandProperty Name
if (-not $reviewJs) { $reviewJs = 'unknown' }
$versionText = @(
  "built_at=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
  "main_js=$mainJs"
  "review_js=$reviewJs"
) -join "`n"
Set-Content -LiteralPath (Join-Path $web 'dist\VERSION.txt') -Value $versionText -Encoding UTF8
Copy-Item (Join-Path $web 'dist\VERSION.txt') (Join-Path $stage 'dist\VERSION.txt')

if (Test-Path $tarballLocal) { Remove-Item $tarballLocal -Force }
if (Test-Path $tarballDesktop) { Remove-Item $tarballDesktop -Force }
$tarballLocalGz = Join-Path $release 'dojo-web-release.tar.gz'
$tarballDesktopGz = Join-Path $desktop 'dojo-web-release.tar.gz'
if (Test-Path $tarballLocalGz) { Remove-Item $tarballLocalGz -Force }
if (Test-Path $tarballDesktopGz) { Remove-Item $tarballDesktopGz -Force }

Set-Location $release
tar -czf $tarballName dojo-web-release
Copy-Item $tarballLocal $tarballLocalGz -Force
Copy-Item $tarballLocal $tarballDesktop -Force
Copy-Item $tarballLocalGz $tarballDesktopGz -Force

Write-Host ''
Write-Host "Release (.tgz):  $tarballDesktop"
Write-Host "Release (.tar.gz): $tarballDesktopGz"
Write-Host "Also:            $tarballLocal / $tarballLocalGz"
Write-Host "VERSION.txt main_js=$mainJs"
Get-Item $tarballDesktop | Format-List FullName, Length, LastWriteTime
