# Pack Dojo release for Ubuntu deploy
$ErrorActionPreference = 'Stop'
$nodeDir = 'C:\coding\.tools\node'
if (Test-Path $nodeDir) { $env:PATH = "$nodeDir;" + $env:PATH }

$root = 'C:\coding\Dojo'
$web = "$root\dojo-web"
$release = "$root\release"
$stage = "$release\dojo-web-release"

Set-Location $web

$envLocal = "$web\.env.local"
$envProdLocal = "$web\.env.production.local"
if (Test-Path $envLocal) {
  $lines = Get-Content $envLocal | Where-Object { $_ -match '^VITE_(DEEPSEEK|RAPIDAPI)_' }
  @('# auto-generated by pack-release.ps1') + $lines | Set-Content -Path $envProdLocal -Encoding UTF8
  Write-Host '>> .env.production.local (keys in bundle)'
} elseif (Test-Path $envProdLocal) {
  Remove-Item $envProdLocal -Force
}

Write-Host '>> pnpm build'
pnpm build
if ($LASTEXITCODE -ne 0) { throw 'pnpm build failed' }

Write-Host '>> stage release'
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Path $stage | Out-Null
Copy-Item -Recurse "$web\dist" "$stage\dist"
Copy-Item "$root\scripts\deploy\nginx-dojo.conf" "$stage\nginx-dojo.conf"
Copy-Item "$root\scripts\deploy\install-on-server.sh" "$stage\install-on-server.sh"
Copy-Item "$root\scripts\deploy\secrets.env.example" "$stage\secrets.env.example"

$secretsOut = "$stage\secrets.env"
if (Test-Path $envLocal) {
  $m1 = Select-String -Path $envLocal -Pattern '^VITE_DEEPSEEK_API_KEY=(.+)$' | Select-Object -First 1
  $m2 = Select-String -Path $envLocal -Pattern '^VITE_RAPIDAPI_KEY=(.+)$' | Select-Object -First 1
  $ds = if ($m1) { $m1.Matches.Groups[1].Value } else { $null }
  $rp = if ($m2) { $m2.Matches.Groups[1].Value } else { $null }
  if ($ds -and $rp) {
    @("DEEPSEEK_API_KEY=$ds", "RAPIDAPI_KEY=$rp") | Set-Content -Path $secretsOut -Encoding UTF8
    Write-Host '>> secrets.env for nginx'
  }
}

$tarball = "$release\dojo-web-release.tar.gz"
if (Test-Path $tarball) { Remove-Item $tarball -Force }

Set-Location $release
tar -czf dojo-web-release.tar.gz dojo-web-release

Write-Host ''
Write-Host "Release: $tarball"
