# Pack Dojo redesign release for Ubuntu deploy → Desktop\dojo-web-release.tgz
$ErrorActionPreference = 'Stop'
$OutputEncoding = [Console]::OutputEncoding = [Text.Encoding]::UTF8

$deployDir = $PSScriptRoot
$root = (Resolve-Path (Join-Path $deployDir '..\..')).Path
$web = Join-Path $root 'dojo-web-redesign'
if (-not (Test-Path (Join-Path $web 'package.json'))) {
  $web = Join-Path $root 'dojo-web'
}
$release = Join-Path $root 'release'
$stage = Join-Path $release 'dojo-web-release'
$desktop = [Environment]::GetFolderPath('Desktop')
$tarballName = 'dojo-web-release.tgz'
$tarballDesktop = Join-Path $desktop $tarballName
$tarballLocal = Join-Path $release $tarballName

Write-Host ">> root = $root"
Write-Host ">> web  = $web"

Set-Location $web

# 生产走 Nginx 反代，禁止把密钥打进前端包
$prodLocalFile = Join-Path $web '.env.production.local'
@('# auto-generated by pack-release.ps1 — 密钥只进 secrets.env，不进 bundle') |
  Set-Content -LiteralPath $prodLocalFile -Encoding UTF8
Write-Host '>> .env.production.local cleared (proxy-only build)'

Write-Host '>> vue-tsc + vite build'
$bin = Join-Path $web 'node_modules\.bin'
$vueTsc = Join-Path $bin 'vue-tsc.CMD'
$vite = Join-Path $bin 'vite.CMD'
if (-not (Test-Path $vueTsc)) { throw "vue-tsc not found: $vueTsc" }
if (-not (Test-Path $vite)) { throw "vite not found: $vite" }

& $vueTsc --noEmit
if ($LASTEXITCODE -ne 0) { throw 'vue-tsc failed' }
& $vite build
if ($LASTEXITCODE -ne 0) { throw 'vite build failed' }

Write-Host '>> stage release'
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Path $stage | Out-Null
Copy-Item -Recurse (Join-Path $web 'dist') (Join-Path $stage 'dist')
Copy-Item (Join-Path $deployDir 'nginx-dojo.conf') (Join-Path $stage 'nginx-dojo.conf')
Copy-Item (Join-Path $deployDir 'install-on-server.sh') (Join-Path $stage 'install-on-server.sh')
Copy-Item (Join-Path $deployDir 'secrets.env.example') (Join-Path $stage 'secrets.env.example')
Copy-Item (Join-Path $deployDir 'server-apply-seed.sh') (Join-Path $stage 'server-apply-seed.sh') -ErrorAction SilentlyContinue

# 确保种子进包（vite 一般会从 public 拷到 dist；再兜底一次）
$seedSrc = Join-Path $web 'public\dojo-seed.json'
$seedDist = Join-Path $stage 'dist\dojo-seed.json'
if ((Test-Path $seedSrc) -and -not (Test-Path $seedDist)) {
  Copy-Item $seedSrc $seedDist
  Write-Host '>> copied dojo-seed.json into dist'
}

# 可选：从本机 .env.local 抽出密钥，仅供服务器 nginx secrets.env（不进 dist）
$dotenvLocalPath = Join-Path $web '.env.local'
$secretsOut = Join-Path $stage 'secrets.env'
if (Test-Path -LiteralPath $dotenvLocalPath) {
  $content = Get-Content -LiteralPath $dotenvLocalPath
  $ds = $null
  $rp = $null
  foreach ($line in $content) {
    if ($line -match '^(?:VITE_)?DEEPSEEK_API_KEY\s*=\s*(.+)$') {
      $ds = $Matches[1].Trim().Trim('"').Trim("'")
    }
    if ($line -match '^(?:VITE_)?RAPIDAPI_KEY\s*=\s*(.+)$') {
      $rp = $Matches[1].Trim().Trim('"').Trim("'")
    }
  }
  if ($ds -and $rp -and $ds -notmatch 'REPLACE' -and $rp -notmatch 'REPLACE') {
    @("DEEPSEEK_API_KEY=$ds", "RAPIDAPI_KEY=$rp") | Set-Content -LiteralPath $secretsOut -Encoding UTF8
    Write-Host '>> secrets.env (for nginx only)'
  } else {
    Write-Host '>> skip secrets.env (no valid keys in .env.local)'
  }
}

# 写入 VERSION.txt，便于服务器 curl 验收
$indexHtml = Join-Path $web 'dist\index.html'
$mainJs = if (Test-Path $indexHtml) {
  $m = Select-String -Path $indexHtml -Pattern 'src="/assets/(index-[^"]+\.js)"' | Select-Object -First 1
  if ($m) { $m.Matches.Groups[1].Value } else { 'unknown' }
} else { 'unknown' }
$versionText = @(
  "built_at=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
  "source=dojo-web-redesign"
  "main_js=$mainJs"
  "host_hint=129.226.147.77"
) -join "`n"
Set-Content -LiteralPath (Join-Path $web 'dist\VERSION.txt') -Value $versionText -Encoding UTF8
Copy-Item (Join-Path $web 'dist\VERSION.txt') (Join-Path $stage 'dist\VERSION.txt') -Force

# 桌面安装说明
$readme = @"
# Dojo 2049 改版发布包

目标服务器: 129.226.147.77

## 上传并安装

1. 把本目录旁的 dojo-web-release.tgz 上传到服务器 /root/
2. SSH 登录后执行:

\`\`\`bash
tar -xzf /root/dojo-web-release.tgz -C /tmp
bash /tmp/dojo-web-release/install-on-server.sh
\`\`\`

3. 若 /etc/dojo/secrets.env 首次创建，按提示填密钥后，再跑一次 install-on-server.sh
4. 打开 http://129.226.147.77/ ，登录 Super / 123456
5. 业务种子: dist/dojo-seed.json（首访空浏览器会自动灌入）

## 可选：仅刷新种子

\`\`\`bash
bash /tmp/dojo-web-release/server-apply-seed.sh
\`\`\`
"@
Set-Content -LiteralPath (Join-Path $stage 'README-DEPLOY.txt') -Value $readme -Encoding UTF8

if (-not (Test-Path $release)) { New-Item -ItemType Directory -Path $release | Out-Null }
if (Test-Path $tarballLocal) { Remove-Item $tarballLocal -Force }
if (Test-Path $tarballDesktop) { Remove-Item $tarballDesktop -Force }
$tarballLocalGz = Join-Path $release 'dojo-web-release.tar.gz'
$tarballDesktopGz = Join-Path $desktop 'dojo-web-release.tar.gz'
if (Test-Path $tarballLocalGz) { Remove-Item $tarballLocalGz -Force }
if (Test-Path $tarballDesktopGz) { Remove-Item $tarballDesktopGz -Force }

Set-Location $release
tar -czf $tarballName dojo-web-release
Copy-Item $tarballLocal $tarballLocalGz -Force
Copy-Item $tarballLocal $tarballDesktop -Force
Copy-Item $tarballLocalGz $tarballDesktopGz -Force

# 额外：把解压目录也拷到桌面，方便直接看内容
$desktopFolder = Join-Path $desktop 'dojo-web-release'
if (Test-Path $desktopFolder) { Remove-Item $desktopFolder -Recurse -Force }
Copy-Item -Recurse $stage $desktopFolder

Write-Host ''
Write-Host "Release (.tgz):  $tarballDesktop"
Write-Host "Release (.tar.gz): $tarballDesktopGz"
Write-Host "Folder:          $desktopFolder"
Write-Host "Also:            $tarballLocal / $tarballLocalGz"
Write-Host "VERSION.txt main_js=$mainJs"
Get-Item $tarballDesktop | Format-List FullName, Length, LastWriteTime
